import { createGlobalThemeContract } from '@vanilla-extract/css';

export const vars = createGlobalThemeContract({
  color: {
    bgDefault: 'pm3-color-bg-default',
    bgSurface: 'pm3-color-bg-surface',
    bgSurfaceHover: 'pm3-color-bg-surface-hover',
    bgInverse: 'pm3-color-bg-inverse',
    textDefault: 'pm3-color-text-default',
    textSubtle: 'pm3-color-text-subtle',
    textDisabled: 'pm3-color-text-disabled',
    textInverse: 'pm3-color-text-inverse',
    textBrand: 'pm3-color-text-brand',
    borderSubtle: 'pm3-color-border-subtle',
    borderDefault: 'pm3-color-border-default',
    borderStrong: 'pm3-color-border-strong',
    borderFocus: 'pm3-color-border-focus',
    actionPrimaryBg: 'pm3-color-action-primary-bg',
    actionPrimaryBgHover: 'pm3-color-action-primary-bg-hover',
    actionPrimaryText: 'pm3-color-action-primary-text',
    actionSecondaryBg: 'pm3-color-action-secondary-bg',
    actionSecondaryBgHover: 'pm3-color-action-secondary-bg-hover',
    actionSecondaryText: 'pm3-color-action-secondary-text',
    actionDisabledBg: 'pm3-color-action-disabled-bg',
    actionDisabledText: 'pm3-color-action-disabled-text',
  },
  spacing: {
    s0: 'pm3-spacing-spacing0',
    s2: 'pm3-spacing-spacing2',
    s4: 'pm3-spacing-spacing4',
    s8: 'pm3-spacing-spacing8',
    s12: 'pm3-spacing-spacing12',
    s16: 'pm3-spacing-spacing16',
    s20: 'pm3-spacing-spacing20',
    s24: 'pm3-spacing-spacing24',
    s32: 'pm3-spacing-spacing32',
    s40: 'pm3-spacing-spacing40',
  },
  radius: {
    r0: 'pm3-radius-radius0',
    r2: 'pm3-radius-radius2',
    r4: 'pm3-radius-radius4',
    r8: 'pm3-radius-radius8',
    r12: 'pm3-radius-radius12',
    r16: 'pm3-radius-radius16',
    full: 'pm3-radius-radius-full',
  },
  typography: {
    fontFamilyBrand: 'pm3-typography-font-family-brand',
    fontSizeBodyMedium: 'pm3-typography-font-size-body-medium',
    fontSizeBodyLarge: 'pm3-typography-font-size-body-large',
    fontSizeLabelMedium: 'pm3-typography-font-size-label-medium',
    fontSizeLabelLarge: 'pm3-typography-font-size-label-large',
    lineHeightBodyMedium: 'pm3-typography-line-height-body-medium',
    lineHeightBodyLarge: 'pm3-typography-line-height-body-large',
  }
});
